# Generated by Django 6.0.1 on 2026-02-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pages', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
